// Russian texts
let ru = {
  // verb
  add: 'добавить',
  create: 'создать',
  change: 'изменить',
  clear: 'очистить',
  delete: 'удалить',
  deduplicate: 'дедуплицировать',
  edit: 'редактировать',
  enable: 'включить',
  forget: 'забыть',
  save: 'сохранить',
  take: 'принять',
  select: 'выбрать',
  remember: '',
  restore: 'восстановить',
  require: 'требовать',
  update: 'обновить',
  use: 'использовать',
  view: 'просмотр',
  want: 'хотите',
  // adjective
  acknowledge: 'подтверждение',
  acknowledged: 'подтверждено',
  not_acknowledged: 'не подтверждено',
  only_acknowledged: 'только подтвержденные',
  only_unacknowledged: 'только не подтвержденные',
  active: 'активный | активная | активное',
  advanced: 'дополнительные',
  as: 'как',
  created: 'создано',
  detected: 'обнаружен',
  enabled: 'активный',
  failed: 'неудачный',
  face: 'лицо',
  found: 'найден | найдены | найдено',
  not_found: 'не найден | не найдена | не найдено',
  has_no_match: 'Без совпадений',
  has_match: 'Только совпадения',
  only_with_matches: 'Только совпадения',
  only_without_matches: 'Без совпадений',
  no_match: 'нет совпадений',
  important: 'важный',
  local: 'локальный | локальная',
  login: 'логин',
  new: 'новый | новая',
  matched_to: 'похож на',
  modified: 'обновлено',
  next: 'следующий',
  previous: 'предыдущий',
  success: 'успешное | успешный',
  or: 'или',
  selected: 'выбраны',
  not_selected: 'не выбраны',
  taked: 'принятые',
  not_taked: 'Непринятые',
  was_updated: 'обновлен | обновлено',
  was_created: 'создан | создано',
  with: 'c',
  uploaded: 'загружены',
  // noun
  acknowledgement: 'подтверждение',
  event_acknowledgement: 'подтверждение',
  action: 'действие',
  admin: 'администратор',
  administrator: 'администратор',
  alert: 'оповещение | оповещения',
  all: 'все',
  back: 'назад',
  batch: 'пакетная',
  batch_upload_leave_confirm: 'Пакетная загрузка будет прервана если вы покините страницу. Прокинуть?',
  camera_pf: 'камера | камеры | камер',
  connected_pf: 'подключена | подключены | подключено',
  camera: 'камера | камеру | камере | камерой | камере',
  camera_group: 'группа камер | группу камер',
  camera_groups: 'группы камер',
  cameras: 'камеры',
  cancel: 'отмена',
  comment: 'комментарий | комментария',
  confirm_password: 'подтверждение пароля',
  confidence: 'точность распознавания',
  dashboard: 'доска',
  datetime: 'время',
  detector: 'детектор',
  deduplicate_delay: 'интервал дедупликации',
  dossier: 'досье',
  dossiers: 'досье',
  dossier_list: 'список наблюдения | списка наблюдения',
  dossier_lists: 'списки наблюдения | списков наблюдения',
  end: 'конец',
  error: 'ошибка',
  errors: 'ошибки',
  event: 'событие | события',
  events: 'события',
  filename: 'имя файла',
  file: 'файл | файла',
  files: 'файлы | файлов',
  filter: 'фильтр',
  filters: 'фильтры',
  folder: 'директория | директорию',
  group: 'группа',
  height: 'высота',
  image: 'изображение',
  items: 'результаты | результатов',
  in_progress: 'обрабатывается',
  in_queue: 'в очереди',
  label: 'метка',
  loading: 'загрузка',
  logout: 'выход',
  manager: 'менеджер',
  match: 'совпадения',
  matches: 'совпадений | совпадения',
  meta: 'мета',
  name: 'имя | имени',
  no: 'нет',
  notify: 'оповещение | оповещения',
  page: 'страница',
  parameters: 'параметры',
  password: 'пароль',
  phone: 'телефон',
  photo: 'фотография | фотографию',
  photo_delete_confirm: 'Вы хотите удалить фото?',
  photos: 'фотографии',
  prefix: 'префикс',
  postfix: 'постфикс',
  ok: 'ok',
  operator: 'оператор',
  report: 'отчет',
  reports: 'отчеты',
  reset: 'сброс',
  roi: 'регион захвата лица',
  role: 'роль',
  rot: 'регион слежения',
  upload: 'загрузка',
  user: 'пользователь | пользователя | пользователю | пользователем | пользователе',
  users: 'пользователи',
  search: 'поиск',
  search_location: 'Место поиска',
  search_looks_like: 'искать похожих на',
  security: 'сотрудник СБ',
  social_nets: 'социальные сети',
  sign_in: 'вход',
  size: 'размер',
  sound: 'звук',
  sound_aj: 'звуковой | звуковая | звуковое',
  source: 'источник',
  start: 'cтарт',
  status: 'статус',
  threshold: 'порог',
  stop: 'стоп',
  type: 'тип',
  url: 'url',
  warning: 'предупреждение',
  width: 'ширина',
  you: 'вы',
  yes: 'да',
  // phrases
  license_agreement: 'Лицензионное соглашение',
  accept_license_agreement: 'Я принимаю условия лицензионного соглашения',
  proceed: 'Продолжить'
}

// English
let en = {
  // verb
  activate: 'активировать',
  add: 'add',
  create: 'create',
  change: 'change',
  clear: 'clear',
  delete: 'delete',
  deduplicate: 'deduplicate',
  edit: 'edit',
  enable: 'enable',
  forget: 'forget',
  save: 'save',
  select: 'select',
  take: 'take',
  remember: 'remember',
  restore: 'restore',
  require: 'require',
  update: 'update',
  use: 'use',
  view: 'view',
  want: 'want',
  // adjective
  alert: 'alert',
  acknowledge: 'acknowledge',
  acknowledged: 'acknowledged',
  not_acknowledged: 'not acknowledged',
  only_acknowledged: 'only acknowledged',
  only_unacknowledged: 'only unacknowledged',
  active: 'active',
  advanced: 'advanced',
  as: 'as',
  created: 'created',
  detected: 'detected',
  enabled: 'enabled',
  failed: 'failed',
  found: 'found',
  not_found: 'not found',
  has_no_match: 'Has no match',
  no_match: 'no match',
  has_match: 'Has match',
  only_with_matches: 'only with matches',
  only_without_matches: 'only without matches',
  important: 'important',
  local: 'local',
  matched_to: 'matched to',
  modified: 'modified',
  new: 'new',
  next: 'next',
  or: 'or',
  previous: 'previous',
  success: 'success',
  selected: 'selected',
  not_selected: 'not selected',
  taked: 'accepted',
  not_taked: 'not accepted',
  was_updated: 'updated',
  was_created: 'created',
  with: 'with',
  uploaded: 'uploaded',
  // noun
  acknowledgement: 'acknowledgement',
  event_acknowledgement: 'event acknowledgement',
  action: 'action',
  admin: 'administrator',
  administrator: 'administrator',
  all: 'all',
  back: 'back',
  batch: 'batch',
  batch_upload_leave_confirm: 'Batch upload will be cancelled if you leave the page. Continue?',
  camera: 'camera',
  cameras: 'cameras',
  camera_group: 'camera group',
  camera_groups: 'camera groups',
  cancel: 'cancel',
  comment: 'comment',
  confirm_password: 'confirm password',
  confidence: 'confidence',
  dashboard: 'dashboard',
  datetime: 'time',
  detector: 'detector',
  deduplicate_delay: 'deduplication interval',
  dossier: 'dossier',
  dossiers: 'dossiers',
  dossier_list: 'watch list',
  dossier_lists: 'watch lists',
  end: 'end',
  email: 'email',
  error: 'error',
  errors: 'errors',
  event: 'event',
  events: 'events',
  face: 'face',
  filename: 'filename',
  file: 'file',
  files: 'files',
  filter: 'filter',
  filters: 'filters',
  folder: 'folder',
  group: 'group',
  height: 'height',
  id: 'id',
  image: 'image',
  in_progress: 'in progress',
  in_queue: 'in queue',
  items: 'items',
  label: 'label',
  loading: 'loading',
  login: 'login',
  logout: 'logout',
  manager: 'manager',
  match: 'match',
  matches: 'matches',
  meta: 'meta',
  name: 'name',
  no: 'no',
  notify: 'notify',
  page: 'page',
  parameters: 'parameters',
  password: 'password',
  phone: 'phone',
  photo: 'photo',
  photo_delete_confirm: '',
  photos: 'photos',
  prefix: 'prefix',
  postfix: 'postfix',
  ok: 'ok',
  operator: 'operator',
  report: 'report',
  reports: 'reports',
  reset: 'reset',
  roi: 'Region of Interest',
  role: 'role',
  rot: 'Region of Tracking',
  upload: 'upload',
  url: 'url',
  user: 'user',
  users: 'users',
  security: 'security',
  sign_in: 'sign in',
  size: 'size',
  sound: 'sound',
  sound_aj: 'sound',
  source: 'source',
  start: 'start',
  status: 'status',
  search: 'search',
  search_location: 'search in',
  search_looks_like: 'search looks like',
  social_nets: 'social networks',
  stop: 'stop',
  type: 'type',
  threshold: 'threshold',
  warning: 'warning',
  width: 'width',
  you: 'you',
  yes: 'yes',
  // phrases
  license_agreement: 'license agreement',
  accept_license_agreement: 'I accept the License Agreement',
  proceed: 'Proceed'
}

// Chinese (simplify) texts
let cn = {
  // verb
  activate: 'активировать',
  add: 'add',
  create: 'create',
  change: 'change',
  clear: 'clear',
  delete: 'delete',
  deduplicate: 'deduplicate',
  edit: 'edit',
  enable: 'enable',
  forget: 'forget',
  save: 'save',
  select: 'select',
  take: 'take',
  remember: 'remember',
  restore: 'restore',
  require: 'require',
  update: 'update',
  use: 'use',
  view: 'view',
  want: 'want',
  // adjective
  alert: 'alert',
  acknowledge: 'acknowledge',
  acknowledged: 'acknowledged',
  not_acknowledged: 'not acknowledged',
  only_acknowledged: 'only acknowledged',
  only_unacknowledged: 'only unacknowledged',
  active: 'active',
  advanced: 'advanced',
  as: 'as',
  created: 'created',
  detected: 'detected',
  enabled: 'enabled',
  failed: 'failed',
  found: 'found',
  not_found: 'not found',
  has_no_match: 'Has no match',
  no_match: 'no match',
  has_match: 'Has match',
  only_with_matches: 'only with matches',
  only_without_matches: 'only without matches',
  important: 'important',
  local: 'local',
  matched_to: 'matched to',
  modified: 'modified',
  new: 'new',
  next: 'next',
  or: 'or',
  previous: 'previous',
  success: 'success',
  selected: 'selected',
  not_selected: 'not selected',
  taked: 'accepted',
  not_taked: 'not accepted',
  was_updated: 'updated',
  was_created: 'created',
  with: 'with',
  uploaded: 'uploaded',
  // noun
  acknowledgement: 'acknowledgement',
  event_acknowledgement: 'event acknowledgement',
  action: 'action',
  admin: 'administrator',
  administrator: 'administrator',
  all: 'all',
  back: 'back',
  batch: 'batch',
  batch_upload_leave_confirm: 'Batch upload will be cancelled if you leave the page. Continue?',
  camera: 'camera',
  cameras: 'cameras',
  camera_group: 'camera group',
  camera_groups: 'camera groups',
  cancel: 'cancel',
  comment: 'comment',
  confirm_password: 'confirm password',
  confidence: 'confidence',
  dashboard: 'dashboard',
  datetime: 'time',
  detector: 'detector',
  deduplicate_delay: 'deduplication interval',
  dossier: 'dossier',
  dossiers: 'dossiers',
  dossier_list: 'watch list',
  dossier_lists: 'watch lists',
  end: 'end',
  email: 'email',
  error: 'error',
  errors: 'errors',
  event: 'event',
  events: 'events',
  face: 'face',
  filename: 'filename',
  file: 'file',
  files: 'files',
  filter: 'filter',
  filters: 'filters',
  folder: 'folder',
  group: 'group',
  height: 'height',
  id: 'id',
  image: 'image',
  in_progress: 'in progress',
  in_queue: 'in queue',
  items: 'items',
  label: 'label',
  loading: 'loading',
  login: 'login',
  logout: 'logout',
  manager: 'manager',
  match: 'match',
  matches: 'matches',
  meta: 'meta',
  name: 'name',
  no: 'no',
  notify: 'notify',
  page: 'page',
  parameters: 'parameters',
  password: 'password',
  phone: 'phone',
  photo: 'photo',
  photo_delete_confirm: '',
  photos: 'photos',
  prefix: 'prefix',
  postfix: 'postfix',
  ok: 'ok',
  operator: 'operator',
  report: 'report',
  reports: 'reports',
  reset: 'reset',
  roi: 'Region of Interest',
  role: 'role',
  rot: 'Region of Tracking',
  upload: 'upload',
  url: 'url',
  user: 'user',
  users: 'users',
  security: 'security',
  sign_in: 'sign in',
  size: 'size',
  sound: 'sound',
  sound_aj: 'sound',
  source: 'source',
  start: 'start',
  status: 'status',
  search: 'search',
  search_location: 'search in',
  search_looks_like: 'search looks like',
  settings: 'settings',
  social_nets: 'social networks',
  stop: 'stop',
  type: 'type',
  threshold: 'threshold',
  warning: 'warning',
  width: 'width',
  you: 'you',
  yes: 'yes',
  // phrases
  license_agreement: 'license agreement',
  accept_license_agreement: 'I accept the License Agreement',
  proceed: 'Proceed'
}

export {en, ru, cn}
